name: Notify Pushover on Commit

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pushover-relay notification
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.RELAY_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/bchilton9/pushover-relay/dispatches \
            -d '{
              "event_type": "pushover",
              "client_payload": {
                "title": "📦 New Commit to ${{ github.repository }}",
                "message": "**${{ github.actor }}** pushed:\n${{ github.event.head_commit.message }}\n\n🔗 https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
              }
            }'
